module Buyers
  module PvhTommy
    class Mapper
      def self.build_excel_row(header, line_item)
        {
          "factory" => nil,
          "ship_under_po_ref" => header["po_number"] || nil,
          "article" => nil,
          "buyer" => "TOMMY HILFIGER EUROPE BV",
          "buyer_division_dept" => header["product_division"] || nil,
          "currency" => header["currency"] || nil,
          "season" => nil,
          "country_of_origin" => "INDIA",
          "place_of_receipt_by_pre_carrier" => header["consignee"]&.upcase || nil,
          "prod_capacity_booking_no" => nil,
          "order_initiation_date" => nil,
          "payment_terms" => header["pay_terms"] || nil,
          "buyer_po_num" => header["po_number"] || nil,
          "summary_buyer_order_ref" => nil,
          "market_buyer_order_ref" => nil,
          "destination_buyer_order_ref" => header["po_number"] || nil,
          "delivery_buyer_order_ref" => nil,
          "buyer_order_date" => header["buyer_order_date"] || nil,
          "order_type" => "Confirmed",
          "mode_of_shipment" => header["ship_mode"] || nil,
          "buyer_delivery_date" => header["buyer_delivery_date"] || nil,
          "oc_delivery_date" => header["buyer_delivery_date"] || nil,
          "pcd_date" => nil,
          "original_gac_date" => nil,
          "gac_date" => nil,
          "raw_material_eta" => nil,
          "country_of_final_destination" => header["consignee"]&.upcase || nil,
          "final_destination" => header["consignee"]&.upcase || nil,
          "market" => header["buyer"]&.upcase || nil,
          "buyer_style_ref" => line_item["style"] || nil,
          "packing_type" => nil,
          "packing_option_flat_pack" => nil,
          "color" => line_item["ffc_description"] || nil,
          "size" => line_item["size"] || nil,
          "total_qty" => line_item["quantity"] || nil,
          "price" => line_item["cost"] || nil,
          "units" => line_item["total_units"] || nil,
          "delivery_terms" => header["inco_terms"] || nil,
          "zone" => nil,
          "internal_lot_no" => nil,
          "buyer_lot_no" => nil,
          "delivery_ocid" => nil,
          "fulfillment_type" => "Manufacture",
          "initial_pcd_date" => nil,
          "first_buyer_delivery_date" => nil,
          "packing_code" => nil,
          "make_to_stock" => nil,
          "split" => nil,
          "other_instruction" => nil,
          "extra_production_pct" => nil,
          "upcharge" => nil
        }
      end
    end
  end
end
